services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "EcommerceApi!01"
    volumes:
      - sqlserver_data:/var/opt/mssql
    
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_api
    ports:
      - "5000:8080"                         # port host:port container
    environment:                            # variables d'enviro
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=EcommerceDb;User Id=sa;Password=EcommerceApi!01;TrustServerCertificate=True;"
      JwtSettings__Key: "MaCleSecreteUltraSecure1234567890!"
      JwtSettings__Issuer: "EcommerceApi"
      JwtSettings__Audience: "EcommerceApiClients"
      JwtSettings__DurationInMinutes: "60"
    depends_on:
      - sqlserver

volumes:
  sqlserver_data: